@startuml concept
cloud Network as "Local network"
node Server as "Alarm server"
node Client as "Alarm client"
note left of Client
  Running in the XH-C2X module
end note
cloud Internet
node Google as "Google calendar API"

Client --> Network : "Request"
note right of Network
 with Wireless
end note
Network --> Server
Server --> Internet
Internet --> Google
Google ..> Internet
Internet ..> Server
Server ..> Network
Network ..> Client : Response
@enduml